### ISSUE TITLE
svof seems to focus/tree things simultaniously under certain circumstances.

### ISSUE THREAD

**Issue by keneanung** [svof/svof#142]
> Sent By: Deladan On 2/03/4:09
> So I diagnosed and it touched tree and focused off stupidity http://pastebin.com/WUUYdgMy

**Comment by EldFitheach** [comment]
Not 100% sure if this is the issue, but it looks like bleeding is included in the list of treeable affs (https://github.com/svof/svof/blob/3baa829a557a25ceee769822248c5e153961e529/raw-svo.empty.lua#L88), so in this case, it might be that he's configured to tree with any 2 treeable affs (which I think is the default), and it's focusing for the stupidity and touching tree for the bleeding. I'm not sure if there's some reason for bleeding to be listed as treeable, but I can't think of any, especially since it's considered uncurable in svof (so that it's handled outside the priority system).

**Comment by EldFitheach** [comment]
Just did a quick test. With stupdity and some bleeding, with svo.me.disabledtreefunc['any2affs']=true, I just focussed off the stupidity, and after setting svo.me.disabledtreefunc['any2affs']=false, I focussed and touched tree. So that seems to be the culprit.

**Comment by vadi2** [comment]
Yes the issue is tree doesn't take into account what can be (and will be)
focused off - not trivial to integrate why a tree is being used with what
is focus is being used for. You could have a case where you have 2 affs,
and a tree+focus will cure the individual ones.

You could solve it by simply not using tree if you're using focus, but that
would have big ramifications on curing performance - besides the ping
delay, things like stupidity could delay treeing for a very long while,
which is why it hasn't been done so.

**Comment by EldFitheach** [comment]
Well, in this case, the issue is that the system is using both focus and tree when there's only one aff present that either of them can cure. That seems to be happening because it's reading stupidity and bleeding off of the diagnose, counting that as two treeable affs, and accordingly using both focus and tree. If he had stupidity and another treeable aff, then that behavior would be expected.

Is there a reason that it makes sense for bleeding to be included in the list of treeable affs? If not, I think the problem in the log would be simply solved by removing it from that list.

**Comment by vadi2** [comment]
That sounds like the fix, yep.

**Comment by keneanung** [comment]
closed with #175
