### ISSUE TITLE
Herb Defences never register, keeps eating

### ISSUE THREAD

**Issue by tltbdev** [svof/svof#172]
So I don't know if there's a command to get a good hard reset or something to fix these issues but it's feeling ridiculous at this point. First the pipes and now bayberry and hawthorn won't register as defences and just keep eating continually. Also, Mastery is still showing as a chivalry defence?

**Comment by tltbdev** [comment]
See this: http://forums.achaea.com/discussion/4611/help-with-svof#latest


My faith in this system is woefully low.

**Comment by vadi2** [comment]
In a new profile, download the zip and import it as a package (without
unzipping). Then enable GMCP, and restart Mudlet, connect, and do *vinstall*
.

You've got a variety of issues - your prompt is set to something that the
system can't read (hence your kola looping), you also have an error with
the vinstall command and etc. A tangled mess generally happens if people
try to skip around instructions.

**Comment by tltbdev** [comment]
Eventually I did deduce that the prompt seemed to be the problem, or at least since leaving it at default nothing has happened. I did not skip around any instructions which, as written in the documentation provided from this particular project, is "Connect to achaea and use vinstall. Then restart". 

The reason I changed the prompt in the first place is because I didn't see any options for Battlerage in the customprompt provided.

**Comment by keneanung** [comment]
Battlerage is still on the todo list, see #4

**Comment by keneanung** [comment]
@tltbdev does this issue still exist for you or was it fixed with the prompt?

**Comment by keneanung** [comment]
Closing as there's been no answer for a while now
