### ISSUE TITLE
Diag Spamming in Arena

### ISSUE THREAD

**Issue by rzer0knight** [svof/svof#370]
For some reason when I use "dv" to diag in the arena, the system will keep spamming diag to oblivion. Nothing I can do makes it stop. If i use the normal "diag" command its fine, but if I use SVO "dv" it starts spamming.

As soon as I leave Arena and Svo exits arena mode, I can use DV just fine

I'm using Sylvan package 34

**Comment by vadi2** [comment]
Sounds like the diagnose lines in arena were change by the game.

**Comment by rzer0knight** [comment]
I see, so I need to change the lines in the system?

**Comment by QwindorRousseau** [comment]
I actually just attemoted this earlier and it loops outside the arena as well. Adding for release criteria

**Comment by DazedxJoker** [comment]
I just did an attempt at recreating this, with no luck. I did it on the latest pull of the system at the time. With no other scripts (aside from the defaults). Tested with both serverside on and off. However, I did have it happen to me while working on the deaf/blind aff/def issue. I'm guessing the bug is there, we just need to figure out how to recreate it.

**Comment by QwindorRousseau** [comment]
fixed with #435
