### ISSUE TITLE
Monk Transmute

### ISSUE THREAD

**Issue by QwindorRousseau** [svof/svof#404]
Forwarded by Andraste. Monk transmute apparently is having some issues so will need to have a look at it.

**Comment by antar5** [comment]
Not sure what issues he means (it works in its current functionality fine from what I see) - but it does need to be updated to current functionality. You can now transmute any value up to a max of how much health you are missing, instead of increments of 1000. Ex. TRANSMUTE 3400 works (though if you are only missing 1400 hp, you will only transmute 1400 hp). Svof doesn't do this yet.

**Comment by vadi2** [comment]
That should be simple, rip out the code that has to calculate how to batch it :)

**Comment by QwindorRousseau** [comment]
That is more than likely what he meant. Will follow up when I confirm.

**Comment by sdelo1185** [comment]
Issues with both the transmute not firing period once I hit the threshold necessary to start transmuting (not firing period). But yes, the code should also reflect the changes to Transmute

**Comment by antar5** [comment]
Was working with this and found out transmute is still operating the old way ingame. The new functionality I mentioned in was certainly added in (see classlead 10 ingame) so I'm assuming a bug. Messaged Makarios, will update on any response. Would probably hold off on any changes until then.

**Comment by QwindorRousseau** [comment]
Putting it in the other project for now then until we get an update on it.

**Comment by antar5** [comment]
Bug is fixed. Works ingame as classlead states now.

**Comment by QwindorRousseau** [comment]
Alrighty keeping on slate to get done then when we get a couple of the other major issues worked out.
