### ISSUE TITLE
class defences stalling on client side defup after class change

### ISSUE THREAD

**Issue by sheepdog-mcfry** [svof/svof#475]
Class defences seem to no longer work after class changing occurs. Debugging reveals little, more investigation needed. Defences handled by serverside are fine, only defences handled by the client are having an issue

**Comment by sheepdog-mcfry** [comment]
#467 is related to this issue. Will comment on this thread from now

**Comment by druque** [comment]
One extra bit of information related specifically to the selfishness toggle not working.

Getting stunned after this happens reliably fixes it! I think the selfishness/generosity actions are getting stuck in a queue somewhere because after getting stunned once, the system sent selfishness then generosity about 20 times before settling down. the ^sl$ alias worked again after that.

Hopefully that'll give you a place to start looking.

**Comment by sheepdog-mcfry** [comment]
Thanks for the info, will test it later today!
