### ISSUE TITLE
Stun Bug still in but having trouble replicating

### ISSUE THREAD

**Issue by impuxi** [svof/svof#477]
Stun in general seems to mess some things up.
https://ada-young.appspot.com/pastebin/ck6BLMYf

**Comment by DazedxJoker** [comment]
Try to find out what the system was sending that stun blocked, that might help

**Comment by DazedxJoker** [comment]
It looks like whatever the system is trying to send is might be missing an action in the dictionary.

**Comment by QwindorRousseau** [comment]
I think the issue is coming from somewhere that it is trying to reference the definitions for the curing system actions for an action that it wants to complete but it isn't coming up with the action. I am guessing you are doing this while bashing and are using the svo.do() function or adding the do queue in the system and its not matching that action because its for bashing and would not match anything in the curing or defense dictionary. If that is the case then I think that is just going to be a byproduct of how it tracks if something was done. I think @vadi2 might be able to confirm that better than me though.

**Comment by vadi2** [comment]
No clue. This issue report is super vague. 

I'd start by actually looking at what is at `"Script: Main trigger functions"]:582`. If there's nothing wrong there, go get stunned and try and do something to get that message. If you don't get that message, well then there's not much you can do from this really really vague report.
