### ISSUE TITLE
Put tattoo defs under its own subheader

### ISSUE THREAD

**Issue by antar5** [svof/svof#496]
A suggestion to have tattoo def lines listed under a new subheader of "Tattoo defences" when viewing defs, since there are a considerable number of them at this point - would make it cleaner.

**Comment by K1ngSpad3z** [comment]
With the way that tattoos currently work in the system, not all of them can be activated since they are activated on login by default (Boar, Moss, Moon, Ox, Megalith). So this will likely not happen. Will keep this on the list in case we want to do something with it, but I am going to close this, as it isn't an issue with the current system in place.
