### ISSUE TITLE
Remove hamstring from tree pool

### ISSUE THREAD

**Issue by antar5** [svof/svof#497]
Hamstring is in svof's tree pool. It shouldn't be - hamstring is not curable by tree. Needs to be removed. Log: https://ada-young.appspot.com/pastebin/tKP7lXPg

**Comment by K1ngSpad3z** [comment]
Try and get another log. Seems you focused and used tree for anorexia. Not hamstring

**Comment by antar5** [comment]
No. It used tree because the tree for 2 affs scenario was enabled. You can see from this log - anorexia was focused, tree was touched hamstring fit the two aff count number, and it assumed all affs (including hamstring) was cleared on the empty tree touch - when it was not. You can see hamstring fading on its own immediately after.

**Comment by K1ngSpad3z** [comment]
I understand that part. But if hamstring was in the tree table for curing you would have touched tree on the first attack not the second. Which is why I wanted you to grab another log of just hamstring getting hit. Cause if you dont tree on the single hit then its something entirely different than just the tree table

**Comment by antar5** [comment]
It didn't tree on the first hit because I had no scenarios for touching tree when I'm only afflicted with one treeable aff (or specifically hamstring, I suppose). It treed when I had two affs because I had the scenario for two treeable affs enabled.
