### ISSUE TITLE
vupdate does nothing

### ISSUE THREAD

**Issue by Doriel1234** [svof/svof#538]
When I vupdate it checks for the update, recognizes that I'm on 33.4 and the latest is 34, but doesn't do anything after that.

**Comment by K1ngSpad3z** [comment]
vupdate is no longer used in the beta version currently because we do not have a full release yet to provide updates through the function. And since the class based version is no longer receiving updates, that function will not work properly. If you wish to update the beta version you will need to redownload it from github and save it to the spot where you currently have the beta version
