### ISSUE TITLE
Mastery for Knight Classes

### ISSUE THREAD

**Issue by K1ngSpad3z** [svof/svof#655]
Some time ago (not exactly sure when) the Mastery skill was moved from Chivalry to Dual Cutting Weaponmastery skillset. This change needs to be reflected in the def table.

![image](https://user-images.githubusercontent.com/52007085/93876745-51c6ae00-fca5-11ea-9017-3defdce68ead.png)

Needs to happen: Move Mastery defence to Weaponmastery for the dual cutting spec for Knights (Infernal, Paladin, Runewarden)

**Comment by K1ngSpad3z** [comment]
This seems to affect all Knight classes, and need to be changed in the gmcp tracking of the class to recognize the specialization and adding in the def tables accordingly (Possible addition to the gmcp class resource code)

**Comment by TheLastDarkthorne** [comment]
I remember trying this before but couldn't find a way to reload the defence list upon specialisation change, it would work if they change specs then restart but not work when they change specs it wouldn't reflect the changes on-the-fly. It is not much of a problem since they can just leave the mastery unticked on defup and keepup if they don't have the specialisation or have a trigger to do it when they change specs.
I will close the issue but feel free to reopen if something changes about this!
